const categoriesArray = [
  { name: "All Categories", count: 140 },
  { name: "Innovation", count: 39 },
  { name: "Digital Transformation", count: 20 },
  { name: "Finance & FinTech", count: 65 },
  { name: "Business Analytics", count: 30 },
  { name: "Operations", count: 11 },
  { name: "Leadership/HRM", count: 175 },
  { name: "Marketing", count: 34 },
  { name: "Strategy", count: 74 },
  { name: "Technology", count: 4 },
  { name: "General Management", count: 30 },
];

const allCardsData = [
  {
    programName: "General Management for Shipping (Online)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Innovation",
  },
  {
    programName: "General Management for Shipping (Online)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Innovation",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Digital Transformation",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Digital Transformation",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Digital Transformation",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Digital Transformation",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Digital Transformation",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Digital Transformation",
  },
  {
    programName: "Executive PG Diploma Programme in Management",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Finance & FinTech",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Business Analytics",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Business Analytics",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Business Analytics",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Business Analytics",
  },
  {
    programName: "General Management for Shipping (Online",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Operations",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Leadership/HRM",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Leadership/HRM",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Leadership/HRM",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Marketing",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Strategy",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Technology",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Technology",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "Technology",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "General Management",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "General Management",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "General Management",
  },
  {
    programName: "Emerging Leaders Programme (Blended Online Programme)",
    isCertified: true,
    duration: "1 May,2021 - 30 Apr,2020",
    logo: "Will contain some server URL",
    university: "IIM Rohtak",
    courseType: "Hybrid",
    cost: "6726723",
    lastDate: {
      month: "Feb",
      date: "22",
    },
    category: "General Management",
  },
];

export { categoriesArray, allCardsData };
